### ISSUE TITLE
Collection of suggested corrections

### ISSUE THREAD

**Issue by protofarer** [rbwhitaker/rbwhitaker.wikidot.com#6]
Hi,

While going through your tutorials I made note of various things that could use an update/fix.

General suggest/fix:

- Breadcrumbs at bottom of monogame tutorial pages link back to some orphaned tutorial landing page, in other words: http://rbwhitaker.wikidot.com/c-sharp-comments has a breadcrumb and the oldest ancestor "Tutorials" leads to the orphaned page
- It would be nice to have a "Next Tutorial: (tutorial title)" link at the end of each monogame tutorial page

Specific:

1. page: http://rbwhitaker.wikidot.com/c-sharp-operator-overloading
    - location: Bulleted summary, 2nd item
    - remark: A double minus sign `--` was intended but instead a long dash is displayed
    - existing text: "Operator overloading works for these operators: +, -, *, /, %, ++, —, ==, !=, >=, <=, >, and <, and a few others that we haven't talked about before."

2. page: http://rbwhitaker.wikidot.com/c-sharp-events
    - location: section Defining an event
    - remark: Shouldn't strikethrough'ed text be ommitted?
    - existing text: "Raising an event is not hard, and the simplest solution <strikethrough>which has a limitation</strikethrough>is done with the following:"

3. page: http://rbwhitaker.wikidot.com/c-sharp-error-handling
    - location: section: Throwing exceptions
    - remark: It's implicit as to how the exception object `hamburgerException` receives the member `HamburgersEaten`. This may be more advanced than the purposes of the crash course however so it may be okay to leave as is and allow reader to make assumptions.
    - existing text:
```
try
{
    EatSomeHamburgers(32);
}
catch (AteTooManyHamburgersException hamburgerException)
{
    Console.WriteLine(hamburgerException.HamburgersEaten + " is too many hamburgers.");
}
```

4. page: http://rbwhitaker.wikidot.com/c-sharp-file-io
    - location: Bulleted summary, 4th item
    - remark: Missing *what* the contents of file get written to, in this case should be a string
    - existing text: File.WriteAllText(string filePath, string allText); lets you write out the contents of the entire file **in a single** all at once.
    - suggested text: File.WriteAllText(string filePath, string allText); lets you write out the contents of the entire file **into a single string** all at once.

5. page: http://rbwhitaker.wikidot.com/c-sharp-generics
    - location: section Creating a generic class, 2nd code block
    - remark: Mistakenly used `.`
    - existing text: `_items = newItems.`

6. page: http://rbwhitaker.wikidot.com/c-sharp-using-generics
    - location: section "The `List<T>` Class"
    - remark: `}` should be `>`
    - existing text: "When the `List<T}` class was defined, it left a placeholder, which it referred to as T"

7. page: same above
    - location: same above
    - remark: `»` should be `>>`
    - existing text: "We could make a `List<bool>` or a `List<Player>` or a `List<IFileReader>` or even a `List<List<int»` to make a list of lists of numbers."

8. page: same above
    - location: section "Using the `Dictionary` Class
    - remark: "as" should be "has"
    - existing text: "This generic class **as** two generic type parameters."

9. page: http://rbwhitaker.wikidot.com/c-sharp-using-classes
    - location: section Stack vs. the Heap
    - remark: "an" should be "and"
    - existing text: "Here we're passing both an object **an** an int to the GenerateNumberAndCompare method."

10. page: same above
    - location: same above
    - remark: What is the other method besides `GenerateNumberAndCompare`, is it implicit that the 2nd code block occurs within some method (aka in C# everything happens inside a class and its members). Could use clarification.
    - existing text: "The same thing essentially happens with random, and the contents of random is copied and given to GenerateNumberAndCompare, but this is the reference to the object on the heap. **Now both methods** know about the same instance that actually lives on the heap!"

11. page: http://rbwhitaker.wikidot.com/c-sharp-creating-classes
    - location: section Access Modifiers
    - remark: "a million" should be "an additional two thousand"
    - existing text: "According to our rules, **a million points** should have awarded the player with two new lives! But this code fails to do that."

12. page: http://rbwhitaker.wikidot.com/c-sharp-properties
    - location: subsection Auto-Properties
    - remark: Shouldn't strikethrough'ed text be omitted?
    - existing text: "The compiler will generate a related field`<strikethrough>`known as the backing field`</strikethrough>`for you and wire it all up to get and set that field as expected. This allows you to reserve the option to turn it into a full property later on without affecting most of the program."

13. page: http://rbwhitaker.wikidot.com/monogame-drawing-text-with-spritefonts
    - location: section "What's Next"
    - remark: Consider linking to the texture atlas tutorial instead of sprite rotation, since this reflects the order of the monogame tutorial landing page and also the texture atlas tutorial alreay links to sprite rotation itself.

14. page: http://rbwhitaker.wikidot.com/monogame-texture-atlases-3
    - location: main section
    - remark: Shouldn't there be a `using AnimatedSprite`?

15.  page: same above
    - location: same above
    - remark: in previous tutorials the `texture` variable was declared in the constructor, should it be the same here for sake of convention and consistency

16. page: http://rbwhitaker.wikidot.com/monogame-managing-content
    - location: section Managing Content in MonoGame
    - remark: "section" should be "second"
    - existing text: "This **section** option is mostly only used for content that isn't typically made by an artist in another program, such as a sprite font."

**Comment by xotmatrix** [comment]
The `--` rendering as "—" (em dash) problem is also in the bulleted list at the top of:
http://rbwhitaker.wikidot.com/c-sharp-more-math

**Comment by rbwhitaker** [comment]
> The `--` rendering as "—" (em dash) problem is also in the bulleted list at the top of: http://rbwhitaker.wikidot.com/c-sharp-more-math

Fix this one.

**Comment by rbwhitaker** [comment]
@protofarer, I appreciate all the efforts you put in to compiling this list. I'll get them fixed.

**Comment by rbwhitaker** [comment]
Some comments about these as I fix them.

1. The `--` thing is an artifact of Wikidot's parsing. It treats `--` as an em dash. There's a way to escape it, and I've done that one the ones that have been pointed out here, but I can't guarantee there aren't others. So if people find more, please make additional issues here for them so I can fix them.
2. Two `--` in a paragraph results in strikethrough text instead of two em dashes. I don't really want to escape those in the same way as #1, because they're supposed to be em dashes, not two short dashes. I think I could use the HTML entity code `&mdash;` and it would be rendered correctly, but in this case, I opted to change them to commas, as I think that works just fine here.
3. On this item, with the comment about the `HamburgersEaten` thing, I'm not sure I'm following. I had initially thought I might have failed to define the property or initialize it in the constructor, but I checked those and don't see anything amiss. I'd welcome some clarification on it.
4. I believe I've fixed this, but with a couple of other slight tweaks: `File.WriteAllText(string filePath, string allText);` lets you provide the full contents of a file in a single string. `File.WriteAllLines(string filePath, string[] lines);` lets you provide the full contents of a file in a string array, with each string being added on its own line.
5, 6, 7, 8 and 9. Good catch!
10. I've revised it a little by calling out the specific methods that know about it. The missing method was the main method.
11. lol! I got carried away there, didn't I? :D
12. As before, these strikethroughs are completely unintentional. They're supposed to be a phrase offset by hyphens, but when two of those appear in a sentence or paragraph, Wikidot interprets it as strikethrough text. I wish I could turn that off, because I never use strikethrough. But once again, I fixed this by rephrasing the sentence a bit. If you see other strikethrough text, I can virtually guarantee they're all a mistake.
13. Agreed, and done. Not sure why I jumped the order on it, but it should be better now.
14. This is the first one that I'm *not* going to make a change to. A `using` directive allows you to access types within namespaces besides the one you're already in. As long as you put both your main game class and the `AnimatedSprite` in the same namespace, you shouldn't need any additional `using` directives to make it work.
15. I might be missing what you're saying on this one. I *think* it is referring to the `texture` variable that is defined in `LoadContent` here, rather than... as a field in the main game class I think? But in this case, we load the texture and hand it off to the new `AnimatedSprite` instance, and don't need to do anything else with it. So we can keep it a local variable instead of a field in the class itself. But I'm not 100% sure I know what you're asking for, and could easily be missing something.
16. lol! Good find.

I think I've got them all now. At least the ones that I can confirm are a problem. There were a few that I called out as unchanged because I don't think they represent a problem, but more information could change my mind. I know you reported this several months ago, so it probably isn't fresh in your mind anymore.

Anyway, thanks again, @protofarer, for all of the effort you put into this. You've helped add a great deal of polish to these tutorials with your comments!
